### PR TITLE
Try to fix noarch: python

### PR DESCRIPTION
**Pull request by chrisburr**
There is a bug in https://github.com/conda-forge/seaborn-feedstock/pull/19 which prevents `noarch: python` from being applied properly. Hopefully this will fix it.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@conda-forge/seaborn Ready for review. There is a bug in #19 which prevents `noarch: python` from being applied properly to the `seaborn` metapackage.

**Comment by xhochy** [comment]
@chrisburr While you're at it, can you rename the `name` of the recipe to `seaborn-split` and add 

```
extras:
    feedstock-name: seaborn
```

Otherwise not all package tests will be run.

**Comment by croth1** [comment]
@chrisburr, @xhochy what do you say, is this ready for merge?

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
> @chrisburr, @xhochy what do you say, is this ready for merge?

Once rerendered, yes!

**Comment by chrisburr** [comment]
@gatto Thanks for reporting this issue, the fixed build should be available in an hour or two.

**Pull request merged**
