### PR TITLE
Bump version to `0.10.0`, reset build number to `0`, update dependencies

### PR DESCRIPTION
**Pull request by trendelkampschroer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by trendelkampschroer** [comment]
@conda-forge-admin, please rerender

**Comment by croth1** [comment]
Thanks @trendelkampschroer for your work here 👍

**Comment by xhochy** [comment]
Why did this move again from `matplotlib-base` to `matplotlib`? This is now pulling in Qt unconditionally.

**Comment by xhochy** [comment]
Fix for this in https://github.com/conda-forge/seaborn-feedstock/pull/16

**Comment by croth1** [comment]
Sorry, I missed it in the review - that was my bad. Thanks for taking care of it!

**Pull request merged**
