### PR TITLE
Constrain version of heavyweight package

### PR DESCRIPTION
**Pull request by jamesmyatt**
See #34. Needs to be patched into previous releases of `seaborn-base` (See https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/main/recipe).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jamesmyatt** [comment]
@conda-forge-admin, please rerender

**Comment by jamesmyatt** [comment]
@croth1 is this OK?

**Comment by croth1** [comment]
Sorry for ghosting you @jamesmyatt - I have been on a conference the last couple of days and just started catching up! This seems very reasonable to me. @hmaarrfk could you maybe have a second look, just to be sure?

To fix the original problem you reported, we still need to backport these changes via patching IIUC. Will have a quick look at how easy that will be.

**Comment by croth1** [comment]
@jamesmyatt, unfortunately, I will have to ghost you once more, but I will be able to finish this on the weekend, I promise ;)

**Comment by jamesmyatt** [comment]
No problem. It's not urgent except the risk to the momentum.

**Comment by jamesmyatt** [comment]
Once this is merged, I try to look at the patch too.

**Comment by hmaarrfk** [comment]
Looks great

**Comment by croth1** [comment]
I had a look the patching, but I didn't find a way to mimick the exact pinning mechanism we are using in this recipe - I asked for help here: https://github.com/conda-forge/conda-forge.github.io/discussions/2160

**Comment by croth1** [comment]
Ok looks, good. I submitted https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/719 that should allow us to write a patch that brings exactly this change to the older versions. Thanks @jamesmyatt for reporting and submitting the fix. I will take care of the backporting tonight!

**Comment by croth1** [comment]
hmm @hmaarrfk, the package doesn't seem fine:
```
{
  "arch": null,
  "build": "pyhd8ed1ab_1",
  "build_number": 1,
  "constrains": [
    "seaborn 0.13.2 1"
  ],
  "depends": [
    "matplotlib-base >=3.4,!=3.6.1",
    "numpy >=1.20,!=1.24.0",
    "pandas >=1.2",
    "python >=3.8",
    "scipy >=1.7"
  ],
  "license": "BSD-3-Clause",
  "license_family": "BSD",
  "name": "seaborn-base",
  "noarch": "python",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 1714420168400,
  "version": "0.13.2"
}
```

`seaborn 0.13.2 1` does not seem to make sense, shouldn't that be `seaborn 0.13.2 pyhd8ed1ab_1`? Something seems off with the exact pinning here.

```
conda create -n python=3.10 seaborn-base=0.13.2=pyhd8ed1ab_1 seaborn
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package seaborn-base-0.13.2-pyhd8ed1ab_1 has constraint seaborn 0.13.2 1 conflicting with seaborn-0.10.0-py_0

Could not solve for environment specs
The following packages are incompatible
├─ seaborn is requested and can be installed;
└─ seaborn-base ==0.13.2 pyhd8ed1ab_1 is not installable because it requires
   └─ seaborn 0.13.2 1, which conflicts with any installable versions previously reported.
```

**Comment by jaimergp** [comment]
This might be a bad interaction with multi outputs. Might be able to work around with `seaborn {{ PKG_VERSION }} *_{{ PKG_BUILDNUM }}`.

**Comment by croth1** [comment]
seems to be this issue: https://github.com/conda/conda-build/issues/4415

**Pull request merged**
