### PR TITLE
Split recipe into seaborn-base/seaborn

### PR DESCRIPTION
**Pull request by melund**
This PR splits the seaborn into a seaborn-base/seaborn to handle optional dependencies. 

I tried to follow the example from matplotlib. Let see how it goes :)

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by melund** [comment]
@conda-forge-admin, please rerender

**Comment by melund** [comment]
@croth1 I have split the package into seaborn-base/seaborn. Thanks for your suggestions.

**Comment by melund** [comment]
@CJ-Wright How would a migrator look for this. The package version is not changed here, only the build number. 

```
migrator_ts: 1591856538
__migrator:
  kind:
    version
  migration_number:
    1
  build_number:
    1
seaborn:
  - 0.10.1
```

Should the version number at the buttom include the build number?

**Comment by croth1** [comment]
@melund, thanks for the initiative and sorry for the delay - . It looks good to me.  I am unfortunately very busy at the moment. Since I am not an expert with the intricacies of the split, It would be great if somebody of @conda-forge/core could have another look at to make sure.

**Review by croth1 — APPROVED** [review]

**Comment by croth1** [comment]
I think we still need to make a migrator that replaces all dependencies of `seaborn` -> `seaborn-base`.

**Comment by melund** [comment]
> I think we still need to make a migrator that replaces all dependencies of seaborn -> seaborn-base.

I don't understand fine details of version pinning either :) But I don't see why we need to do any migration. For projects depending on "seaborn" nothing has changed in terms of dependencies. 

With this update we just have the extra option of using "seaborn-base" as the dependency to avoid depending on "statsmodels". 

@CJ-Wright: Do we really need a "migrator" here?

**Comment by CJ-Wright** [comment]
We have a migratior that replaces matplotlib with it's base package. Note that this migratior is written in actual code in the regro/cf-scripts repo rather than as yaml.

**Comment by beckermr** [comment]
I wrote that one and can help here. Not today though.

**Comment by ocefpaf** [comment]
> I think we still need to make a migrator that replaces all dependencies of `seaborn` -> `seaborn-base`.

It would be nice.

BTW this PR is ready to go IMO. Thanks @melund and @croth1 for working this out!

**Comment by melund** [comment]
But if we make a migrator (seaborn->seaborn-base) we are implicitly removing statsmodels from all repos the migrator updates. 

To me that seems like a bad thing if projects relied on the full seaborn 'experience'. But I guess it is OK if package maintainers are free to accept or reject the PR.

**Comment by CJ-Wright** [comment]
Right so that is at the crux of the matplotlib migration as well and is a feedstock by feedstock decision.

**Comment by beckermr** [comment]
We send out prs with “suggestion” in the title. Ppl do what they want with them

**Pull request merged**
