### PR TITLE
v0.13.1: fix build system & sync deps

### PR DESCRIPTION
**Pull request by croth1**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
You'll probably have to update the build scripts as well - e.g.
https://github.com/conda-forge/seaborn-feedstock/blob/819cae67b21d0519577ead7232dfd108a46ef4d0/recipe/build_base.sh#L1

**Comment by dhirschfeld** [comment]
...though those build scripts aren't doing anything special so I'd be inclined to inline the install command in the `meta.yaml` itself, as is done in the `staged-recipes/example`:
https://github.com/conda-forge/staged-recipes/blob/f651cb4d3e5223f317a670d163ee3265a525bd73/recipes/example/meta.yaml#L38

**Comment by croth1** [comment]
closes #31

**Comment by croth1** [comment]
hmm, feels like the windows build script is not required for noarch:python and the actual scripts could be removed. Maybe cleaning this up next time 😬

**Pull request merged**
